### ISSUE TITLE
Panel remains empty if the devtools are detached from the browser window.

### ISSUE THREAD

**Issue by cosinusoidally** [nbp/jit-dev-tools#2]
Hi,

This is following over from  https://groups.google.com/forum/#!topic/mozilla.dev.tech.js-engine.internals/COkS3vLfBWo

I am on Ubuntu 12.04 x86_64. When I attempt to use the addon in Firefox nightly (https://hg.mozilla.org/mozilla-central/rev/bfd82015df48 according to about:buildconfig) it does not work. I get the following error in the console:

console.error: jit-dev-tools: 
  Message: TypeError: this.debuggee is undefined
  Stack:
    JitPanel<.onReady@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jit-dev-tools/lib/jit-panel.js:75:5
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
onStateChange@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/dev/panel.js:70:3

I first created a fresh Firefox profile. I then installed the addon from http://people.mozilla.org/~npierron/jit-dev-tools/jit-dev-tools-0.0.1.xpi .

When I open the jit tab in devtools I see
![jit-devtools-screenshot](https://cloud.githubusercontent.com/assets/905043/8129963/a69d7052-1106-11e5-8081-27429fe53b75.png)

The jit tab remains blank. All that happens is that the above error message displays in my console.

**Comment by nbp** [comment]
Ok, based on the screenshot, I was able to reproduce this issue :)

The problem seems to be that `this.debuggee` is not created when we use the dev-tools in a different window.  I guess this is a platform issue.  I will investigate and keep you posted on this bug.

As a temporary solution, you should be able to use the following work-around:
- Open the dev-tools (not the Jit panel)
- Re-attach the dev-tools to the same window.
- Switch to the Jit panel
- Detach the dev tools

**Comment by nbp** [comment]
I opened a bug against the DevTools API: https://bugzilla.mozilla.org/show_bug.cgi?id=1174158

**Comment by cosinusoidally** [comment]
Thanks, the workaround worked for me. Now I just need to make sense of the graphs it is giving me :)
